"""Parasolid XT node layouts (schema V35), from the Parasolid XT Format Reference.

Each entry: node type -> (name, [(field, type code, n_elts)]). Type codes:
d int, n short, u byte, c char, l logical, p pointer, f double, v vector,
i interval, b box, h hvec, w unicode char. n_elts: 0 scalar, 1 variable, n>1 array.

Corrected against real data where the documentation is wrong: FACE lacks the
attributes_features code, HALFEDGE omits loop, ELLIPSE lists centre before sense.

Embedded schema diffs in each file are applied on top of these (see xt.py).
"""

NODES = {
    10: ('ASSEMBLY', [
        ('highest_node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('attribute_chains', 'p', 0),
        ('list', 'p', 0),
        ('lattice', 'p', 0),
        ('surface', 'p', 0),
        ('curve', 'p', 0),
        ('point', 'p', 0),
        ('mesh', 'p', 0),
        ('polyline', 'p', 0),
        ('key', 'p', 0),
        ('res_size', 'f', 0),
        ('res_linear', 'f', 0),
        ('ref_instance', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('state', 'u', 0),
        ('owner', 'p', 0),
        ('type', 'u', 0),
        ('sub_instance', 'p', 0),
        ('mesh_offset_data', 'p', 0),
    ]),
    11: ('INSTANCE', [
        ('node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('type', 'u', 0),
        ('part', 'p', 0),
        ('transform', 'p', 0),
        ('assembly', 'p', 0),
        ('next_in_part', 'p', 0),
        ('prev_in_part', 'p', 0),
        ('next_of_part', 'p', 0),
        ('prev_of_part', 'p', 0),
    ]),
    12: ('BODY', [
        ('highest_node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('attribute_chains', 'p', 0),
        ('lattice', 'p', 0),
        ('surface', 'p', 0),
        ('curve', 'p', 0),
        ('point', 'p', 0),
        ('mesh', 'p', 0),
        ('polyline', 'p', 0),
        ('key', 'p', 0),
        ('res_size', 'f', 0),
        ('res_linear', 'f', 0),
        ('ref_instance', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('state', 'u', 0),
        ('owner', 'p', 0),
        ('body_type', 'u', 0),
        ('nom_geom_state', 'u', 0),
        ('shell', 'p', 0),
        ('boundary_surface', 'p', 0),
        ('boundary_curve', 'p', 0),
        ('boundary_point', 'p', 0),
        ('boundary_mesh', 'p', 0),
        ('boundary_polyline', 'p', 0),
        ('region', 'p', 0),
        ('edge', 'p', 0),
        ('vertex', 'p', 0),
        ('index_map_offset', 'd', 0),
        ('index_map', 'p', 0),
        ('node_id_index_map', 'p', 0),
        ('schema_embedding_map', 'p', 0),
        ('child', 'p', 0),
        ('lowest_node_id', 'd', 0),
        ('mesh_offset_data', 'p', 0),
    ]),
    13: ('SHELL', [
        ('node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('body', 'p', 0),
        ('next', 'p', 0),
        ('face', 'p', 0),
        ('edge', 'p', 0),
        ('vertex', 'p', 0),
        ('region', 'p', 0),
        ('front_face', 'p', 0),
    ]),
    14: ('FACE', [
        ('node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('tolerance', 'f', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('loop', 'p', 0),
        ('shell', 'p', 0),
        ('surface', 'p', 0),
        ('sense', 'c', 0),
        ('next_on_surface', 'p', 0),
        ('previous_on_surface', 'p', 0),
        ('next_front', 'p', 0),
        ('previous_front', 'p', 0),
        ('front_shell', 'p', 0),
    ]),
    15: ('LOOP', [
        ('node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('halfedge', 'p', 0),
        ('face', 'p', 0),
        ('next', 'p', 0),
    ]),
    16: ('EDGE', [
        ('node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('tolerance', 'f', 0),
        ('halfedge', 'p', 0),
        ('previous', 'p', 0),
        ('next', 'p', 0),
        ('curve', 'p', 0),
        ('next_on_curve', 'p', 0),
        ('previous_on_curve', 'p', 0),
        ('owner', 'p', 0),
    ]),
    17: ('HALFEDGE', [
        ('attributes_features', 'p', 0),
        ('loop', 'p', 0),
        ('forward', 'p', 0),
        ('backward', 'p', 0),
        ('vertex', 'p', 0),
        ('other', 'p', 0),
        ('edge', 'p', 0),
        ('curve', 'p', 0),
        ('next_at_vx', 'p', 0),
        ('sense', 'c', 0),
    ]),
    18: ('VERTEX', [
        ('node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('halfedge', 'p', 0),
        ('previous', 'p', 0),
        ('next', 'p', 0),
        ('point', 'p', 0),
        ('tolerance', 'f', 0),
        ('owner', 'p', 0),
    ]),
    19: ('REGION', [
        ('node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('body', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('shell', 'p', 0),
        ('type', 'c', 0),
    ]),
    29: ('POINT', [
        ('node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('owner', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('pvec', 'v', 0),
    ]),
    30: ('LINE', [
        ('node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('owner', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('geometric_owner', 'p', 0),
        ('sense', 'c', 0),
        ('pvec', 'v', 0),
        ('direction', 'v', 0),
    ]),
    31: ('CIRCLE', [
        ('node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('owner', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('geometric_owner', 'p', 0),
        ('sense', 'c', 0),
        ('centre', 'v', 0),
        ('normal', 'v', 0),
        ('x_axis', 'v', 0),
        ('radius', 'f', 0),
    ]),
    32: ('ELLIPSE', [
        ('node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('owner', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('geometric_owner', 'p', 0),
        ('sense', 'c', 0),
        ('centre', 'v', 0),
        ('normal', 'v', 0),
        ('x_axis', 'v', 0),
        ('major_radius', 'f', 0),
        ('minor_radius', 'f', 0),
    ]),
    38: ('INTERSECTION', [
        ('node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('owner', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('geometric_owner', 'p', 0),
        ('sense', 'c', 0),
        ('surface', 'p', 2),
        ('chart', 'p', 0),
        ('start', 'p', 0),
        ('end', 'p', 0),
        ('intersection_data', 'p', 0),
    ]),
    40: ('CHART', [
        ('base_parameter', 'f', 0),
        ('base_scale', 'f', 0),
        ('chart_count', 'd', 0),
        ('chordal_error', 'f', 0),
        ('angular_error', 'f', 0),
        ('parameter_error', 'f', 2),
        ('hvec', 'h', 1),
    ]),
    41: ('LIMIT', [
        ('type', 'c', 0),
        ('term_use', 'c', 0),
        ('hvec', 'h', 1),
    ]),
    45: ('BSPLINE_VERTICES', [
        ('vertices', 'f', 1),
    ]),
    50: ('PLANE', [
        ('node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('owner', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('geometric_owner', 'p', 0),
        ('sense', 'c', 0),
        ('pvec', 'v', 0),
        ('normal', 'v', 0),
        ('x_axis', 'v', 0),
    ]),
    51: ('CYLINDER', [
        ('node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('owner', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('geometric_owner', 'p', 0),
        ('sense', 'c', 0),
        ('pvec', 'v', 0),
        ('axis', 'v', 0),
        ('radius', 'f', 0),
        ('x_axis', 'v', 0),
    ]),
    52: ('CONE', [
        ('node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('owner', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('geometric_owner', 'p', 0),
        ('sense', 'c', 0),
        ('pvec', 'v', 0),
        ('axis', 'v', 0),
        ('radius', 'f', 0),
        ('sin_half_angle', 'f', 0),
        ('cos_half_angle', 'f', 0),
        ('x_axis', 'v', 0),
    ]),
    53: ('SPHERE', [
        ('node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('owner', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('geometric_owner', 'p', 0),
        ('sense', 'c', 0),
        ('centre', 'v', 0),
        ('radius', 'f', 0),
        ('axis', 'v', 0),
        ('x_axis', 'v', 0),
    ]),
    54: ('TORUS', [
        ('node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('owner', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('geometric_owner', 'p', 0),
        ('sense', 'c', 0),
        ('centre', 'v', 0),
        ('axis', 'v', 0),
        ('major_radius', 'f', 0),
        ('minor_radius', 'f', 0),
        ('x_axis', 'v', 0),
    ]),
    56: ('BLENDED_EDGE', [
        ('node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('owner', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('geometric_owner', 'p', 0),
        ('sense', 'c', 0),
        ('blend_type', 'c', 0),
        ('surface', 'p', 2),
        ('spine', 'p', 0),
        ('range', 'f', 2),
        ('thumb_weight', 'f', 2),
        ('boundary', 'p', 2),
        ('start', 'p', 0),
        ('end', 'p', 0),
    ]),
    59: ('BLEND_BOUND', [
        ('node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('owner', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('geometric_owner', 'p', 0),
        ('sense', 'c', 0),
        ('boundary', 'n', 0),
        ('blend', 'p', 0),
    ]),
    60: ('OFFSET_SURF', [
        ('node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('owner', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('geometric_owner', 'p', 0),
        ('sense', 'c', 0),
        ('check', 'c', 0),
        ('true_offset', 'l', 0),
        ('surface', 'p', 0),
        ('offset', 'f', 0),
        ('scale', 'f', 0),
    ]),
    67: ('SWEPT_SURF', [
        ('node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('owner', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('geometric_owner', 'p', 0),
        ('sense', 'c', 0),
        ('section', 'p', 0),
        ('sweep', 'v', 0),
        ('scale', 'f', 0),
    ]),
    68: ('SPUN_SURF', [
        ('node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('owner', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('geometric_owner', 'p', 0),
        ('sense', 'c', 0),
        ('profile', 'p', 0),
        ('base', 'v', 0),
        ('axis', 'v', 0),
        ('start', 'v', 0),
        ('end', 'v', 0),
        ('start_param', 'f', 0),
        ('end_param', 'f', 0),
        ('x_axis', 'v', 0),
        ('scale', 'f', 0),
    ]),
    70: ('LIST', [
        ('node_id', 'd', 0),
        ('list_type', 'u', 0),
        ('notransmit', 'l', 0),
        ('owner', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('list_length', 'd', 0),
        ('block_length', 'd', 0),
        ('size_of_entry', 'd', 0),
        ('finger_index', 'd', 0),
        ('finger_block', 'p', 0),
        ('list_block', 'p', 0),
    ]),
    74: ('POINTER_LIS_BLOCK', [
        ('n_entries', 'd', 0),
        ('index_map_offset', 'd', 0),
        ('next_block', 'p', 0),
        ('entries', 'p', 1),
    ]),
    79: ('ATT_DEF_ID', [
        ('string', 'c', 1),
    ]),
    80: ('ATTRIB_DEF', [
        ('next', 'p', 0),
        ('identifier', 'p', 0),
        ('type_id', 'd', 0),
        ('actions', 'u', 8),
        ('field_names', 'p', 0),
        ('legal_owners', 'l', 14),
        ('fields', 'u', 1),
    ]),
    81: ('ATTRIBUTE', [
        ('node_id', 'd', 0),
        ('definition', 'p', 0),
        ('owner', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('next_of_type', 'p', 0),
        ('previous_of_type', 'p', 0),
        ('fields', 'p', 1),
    ]),
    82: ('INT_VALUES', [
        ('values', 'd', 1),
    ]),
    83: ('REAL_VALUES', [
        ('values', 'f', 1),
    ]),
    84: ('CHAR_VALUES', [
        ('values', 'c', 1),
    ]),
    85: ('POINT_VALUES', [
        ('values', 'v', 1),
    ]),
    86: ('VECTOR_VALUES', [
        ('values', 'v', 1),
    ]),
    87: ('AXIS_VALUES', [
        ('values', 'v', 1),
    ]),
    88: ('TAG_VALUES', [
        ('values', 't', 1),
    ]),
    89: ('DIRECTION_VALUES', [
        ('values', 'v', 1),
    ]),
    90: ('FEATURE', [
        ('node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('owner', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('type', 'u', 0),
        ('first_member', 'p', 0),
    ]),
    91: ('MEMBER_OF_FEATURE', [
        ('dummy_node_id', 'd', 0),
        ('owner', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('next_member', 'p', 0),
        ('previous_member', 'p', 0),
    ]),
    98: ('UNICODE_VALUES', [
        ('values', 'w', 1),
    ]),
    100: ('TRANSFORM', [
        ('node_id', 'd', 0),
        ('owner', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('rotation_matrix', 'f', 9),
        ('translation_vector', 'v', 0),
        ('scale', 'f', 0),
        ('flag', 'd', 0),
        ('perspective_vector', 'v', 0),
        ('precision', 'p', 0),
    ]),
    101: ('WORLD', [
        ('assembly', 'p', 0),
        ('attribute', 'p', 0),
        ('body', 'p', 0),
        ('transform', 'p', 0),
        ('lattice', 'p', 0),
        ('surface', 'p', 0),
        ('curve', 'p', 0),
        ('point', 'p', 0),
        ('mesh', 'p', 0),
        ('polyline', 'p', 0),
        ('alive', 'l', 0),
        ('attrib_def', 'p', 0),
        ('attdef_list', 'p', 0),
        ('highest_id', 'd', 0),
        ('current_id', 'd', 0),
        ('index_map', 'p', 0),
        ('schema_embedding_map', 'p', 0),
        ('mesh_offset_data', 'p', 0),
    ]),
    102: ('KEY', [
        ('char', 'c', 1),
    ]),
    120: ('PE_SURF', [
        ('node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('owner', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('geometric_owner', 'p', 0),
        ('sense', 'c', 0),
        ('type', 'c', 0),
        ('data', 'p', 0),
        ('tf', 'p', 0),
        ('internal_geom', 'p', 1),
    ]),
    121: ('INT_PE_DATA', [
        ('geom_type', 'd', 0),
        ('real_array', 'p', 0),
        ('int_array', 'p', 0),
    ]),
    122: ('EXT_PE_DATA', [
        ('key', 'p', 0),
        ('real_array', 'p', 0),
        ('int_array', 'p', 0),
    ]),
    124: ('B_SURFACE', [
        ('node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('owner', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('geometric_owner', 'p', 0),
        ('sense', 'c', 0),
        ('nurbs', 'p', 0),
        ('data', 'p', 0),
    ]),
    125: ('SURFACE_DATA', [
        ('original_uint', 'i', 0),
        ('original_vint', 'i', 0),
        ('extended_uint', 'i', 0),
        ('extended_vint', 'i', 0),
        ('self_int', 'u', 0),
        ('original_u_start', 'c', 0),
        ('original_u_end', 'c', 0),
        ('original_v_start', 'c', 0),
        ('original_v_end', 'c', 0),
        ('extended_u_start', 'c', 0),
        ('extended_u_end', 'c', 0),
        ('extended_v_start', 'c', 0),
        ('extended_v_end', 'c', 0),
        ('analytic_form_type', 'c', 0),
        ('swept_form_type', 'c', 0),
        ('spun_form_type', 'c', 0),
        ('blend_form_type', 'c', 0),
        ('analytic_form', 'p', 0),
        ('swept_form', 'p', 0),
        ('spun_form', 'p', 0),
        ('blend_form', 'p', 0),
    ]),
    126: ('NURBS_SURF', [
        ('u_periodic', 'l', 0),
        ('v_periodic', 'l', 0),
        ('u_degree', 'n', 0),
        ('v_degree', 'n', 0),
        ('n_u_vertices', 'd', 0),
        ('n_v_vertices', 'd', 0),
        ('u_knot_type', 'u', 0),
        ('v_knot_type', 'u', 0),
        ('n_u_knots', 'd', 0),
        ('n_v_knots', 'd', 0),
        ('rational', 'l', 0),
        ('u_closed', 'l', 0),
        ('v_closed', 'l', 0),
        ('surface_form', 'u', 0),
        ('vertex_dim', 'n', 0),
        ('bspline_vertices', 'p', 0),
        ('u_knot_mult', 'p', 0),
        ('v_knot_mult', 'p', 0),
        ('u_knots', 'p', 0),
        ('v_knots', 'p', 0),
    ]),
    127: ('KNOT_MULT', [
        ('mult', 'n', 1),
    ]),
    128: ('KNOT_SET', [
        ('knots', 'f', 1),
    ]),
    130: ('PE_CURVE', [
        ('node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('owner', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('geometric_owner', 'p', 0),
        ('sense', 'c', 0),
        ('type', 'c', 0),
        ('data', 'p', 0),
        ('tf', 'p', 0),
        ('internal_geom', 'p', 1),
    ]),
    133: ('TRIMMED_CURVE', [
        ('node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('owner', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('geometric_owner', 'p', 0),
        ('sense', 'c', 0),
        ('basis_curve', 'p', 0),
        ('point_1', 'v', 0),
        ('point_2', 'v', 0),
        ('parm_1', 'f', 0),
        ('parm_2', 'f', 0),
    ]),
    134: ('B_CURVE', [
        ('node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('owner', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('geometric_owner', 'p', 0),
        ('sense', 'c', 0),
        ('nurbs', 'p', 0),
        ('data', 'p', 0),
    ]),
    135: ('CURVE_DATA', [
        ('self_int', 'u', 0),
        ('analytic_form', 'p', 0),
    ]),
    136: ('NURBS_CURVE', [
        ('degree', 'n', 0),
        ('n_vertices', 'd', 0),
        ('vertex_dim', 'n', 0),
        ('n_knots', 'd', 0),
        ('knot_type', 'u', 0),
        ('periodic', 'l', 0),
        ('closed', 'l', 0),
        ('rational', 'l', 0),
        ('curve_form', 'u', 0),
        ('bspline_vertices', 'p', 0),
        ('knot_mult', 'p', 0),
        ('knots', 'p', 0),
    ]),
    137: ('SP_CURVE', [
        ('node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('owner', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('geometric_owner', 'p', 0),
        ('sense', 'c', 0),
        ('surface', 'p', 0),
        ('b_curve', 'p', 0),
        ('original', 'p', 0),
        ('tolerance_to_original', 'f', 0),
    ]),
    141: ('GEOMETRIC_OWNER', [
        ('owner', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('shared_geometry', 'p', 0),
    ]),
    163: ('HELIX_SU_FORM', [
        ('axis_pt', 'v', 0),
        ('axis_dir', 'v', 0),
        ('hand', 'c', 0),
        ('turns', 'i', 0),
        ('pitch', 'f', 0),
        ('gap', 'f', 0),
        ('tol', 'f', 0),
    ]),
    176: ('PART_XMT_BLOCK', [
        ('n_entries', 'd', 0),
        ('index_map_offset', 'd', 0),
        ('index_map', 'p', 0),
        ('schema_embedding_map', 'p', 0),
        ('mesh_offset_data', 'p', 0),
        ('entries', 'p', 1),
    ]),
    184: ('HELIX_CU_FORM', [
        ('axis_pt', 'v', 0),
        ('axis_dir', 'v', 0),
        ('point', 'v', 0),
        ('hand', 'c', 0),
        ('turns', 'i', 0),
        ('pitch', 'f', 0),
        ('tol', 'f', 0),
    ]),
    185: ('POLYLINE_DATA', [
        ('n_pvecs', 'd', 0),
        ('base_parm', 'f', 0),
        ('pvec', 'p', 0),
    ]),
    189: ('PSM_MESH', [
        ('precision', 'u', 0),
        ('owner', 'p', 0),
        ('normal_pool', 'p', 0),
        ('position_indices', 'p', 0),
        ('normal_type', 'u', 0),
        ('normal_indices', 'p', 0),
    ]),
    190: ('INTEGER_TOOTH', [
        ('values', 'd', 1),
    ]),
    191: ('INTEGER_COMB', [
        ('encoding', 'u', 0),
        ('n_integers', 'd', 0),
        ('n_max_integers', 'd', 0),
        ('n_bits_per_integer', 'd', 0),
        ('shift', 'd', 0),
        ('teeth', 'p', 1),
    ]),
    192: ('VECTOR_TOOTH', [
        ('values', 'f', 1),
    ]),
    193: ('VECTOR_COMB', [
        ('encoding', 'u', 0),
        ('n_vectors', 'd', 0),
        ('n_max_vectors', 'd', 0),
        ('shift', 'd', 0),
        ('teeth', 'p', 1),
    ]),
    200: ('POLYLINE', [
        ('node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('owner', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('geometric_owner', 'p', 0),
        ('sense', 'c', 0),
        ('data', 'p', 0),
    ]),
    201: ('MESH', [
        ('node_id', 'd', 0),
        ('attributes_features', 'p', 0),
        ('owner', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('geometric_owner', 'p', 0),
        ('sense', 'c', 0),
        ('mesh_box', 'b', 0),
        ('transform', 'p', 0),
        ('rcv_key', 'p', 0),
        ('rcv_index', 'd', 0),
        ('psm_imesh', 'p', 0),
        ('pff_imesh', 'p', 0),
    ]),
    204: ('INTERSECTION_DATA', [
        ('uv_type', 'u', 0),
        ('values', 'f', 1),
    ]),
    205: ('OFFSET_VALUES', [
        ('values', 'd', 1),
    ]),
    206: ('MESH_OFFSET_DATA', [
        ('mesh_index_map', 'p', 0),
        ('schema_data', 'p', 0),
        ('schema_data_offset_high', 'd', 0),
        ('schema_data_offset_low', 'd', 0),
    ]),
    207: ('SCHEMA_CHAR_VALUES', [
        ('values', 'c', 1),
    ]),
    208: ('NEW_NODE_MAP', [
        ('next', 'p', 0),
        ('exemplar_offset_high', 'd', 0),
        ('exemplar_offset_low', 'd', 0),
        ('node_type', 'n', 0),
        ('vla_field_xmt_code', 'l', 0),
        ('name', 'p', 0),
        ('description', 'p', 0),
        ('field_maps', 'p', 1),
    ]),
    209: ('MOD_NODE_MAP', [
        ('next', 'p', 0),
        ('exemplar_offset_high', 'd', 0),
        ('exemplar_offset_low', 'd', 0),
        ('node_type', 'n', 0),
        ('vla_field_xmt_code', 'l', 0),
        ('field_maps', 'p', 1),
    ]),
    210: ('NEW_FIELD_MAP', [
        ('name', 'p', 0),
        ('ptr_class', 'n', 0),
        ('n_elts', 'd', 0),
        ('type', 'p', 0),
    ]),
    211: ('SCHEMA_DATA', [
        ('node_map', 'p', 0),
    ]),
    212: ('OLD_NODE_MAP', [
        ('next', 'p', 0),
        ('exemplar_offset_high', 'd', 0),
        ('exemplar_offset_low', 'd', 0),
        ('node_type', 'n', 0),
    ]),
    213: ('OLD_FIELD_MAP', [
        ('base_index', 'u', 0),
    ]),
    220: ('REAL_TOOTH', [
        ('values', 'd', 1),
    ]),
    221: ('REAL_COMB', [
        ('encoding', 'u', 0),
        ('length', 'd', 0),
        ('max_length', 'd', 0),
        ('shift', 'd', 0),
        ('teeth', 'p', 1),
    ]),
    222: ('LATTICE', [
        ('node_id', 'd', 0),
        ('attributes_feature', 'p', 0),
        ('owner', 'p', 0),
        ('next', 'p', 0),
        ('previous', 'p', 0),
        ('geometric_owner', 'p', 0),
        ('sense', 'c', 0),
        ('data', 'p', 0),
    ]),
    223: ('LATTICE_DATA_IRREGULAR', [
        ('connectivity', 'p', 0),
        ('positions', 'p', 0),
        ('ball_type', 'u', 0),
        ('ball_radius', 'f', 0),
        ('ball_radii', 'p', 0),
        ('ball_rod_radii', 'p', 0),
        ('ball_blend_type', 'u', 0),
        ('ball_blend_size', 'f', 0),
        ('ball_blend_sizes', 'p', 0),
        ('rod_term_type', 'u', 0),
        ('rod_term_radius', 'f', 0),
        ('rod_start_radii', 'p', 0),
        ('rod_end_radii', 'p', 0),
        ('rod_mid_type', 'u', 0),
        ('rod_mid_radius', 'f', 0),
        ('rod_mid_radii', 'p', 0),
    ]),
    224: ('GRAPH_COMPACT', [
        ('adjacency_indices', 'p', 0),
        ('adjacencies', 'p', 0),
    ]),
    229: ('TRANSFORM_PRECISION', [
        ('rotation_matrix', 'f', 0),
        ('translation_vector', 'v', 0),
    ]),
}
